# A Head Start -- Recursos para Curso

Agora que instalamos os softwares mas antes de começar análises com R, aqui são recursos que você pode usar para acelerar sua aprendizagem de R. Já mencionei alguns como o canal YouTube, mas aqui é uma lista sistematizada que você pode consultar para achar ajuda no desenvolvimento das suas habilidades em R.

## Cursos

**HarvardX** (parte do sistema dos cursos à distancia **edX**) oferece uma série dos cursos sobre o uso de R na Ciência dos Dados, PH125. Os primeiros dois cursos neste série: [Data Science: R Basics] (https://www.edx.org/course/data-science-r-basics) e [Data Science: Visualization] (https://www.edx.org/course/data-science-visualization-harvardx-ph125-2x). O professor dos dois é Rafael Irizzary, Chefe de Departamento de Bioestatística do Hospital Dana-Farber de Câncer em Boston e do Escola Chan de Saúde Pública da Universidade Harvard. Você pode fazer cursos de edX de graça em modo de "auditar", que quer dizer que você não recebe certificado se você completa o curso.

Também da Harvard, mas esta vez diretamente da **Escola Chan de Saúde Pública**, tem https://hbctraining.github.io/Intro-to-R/schedules/2_day.html, que tem todas as matérias de um curso de 2 dias sobre R e o Tidyverse. Parece para mim de ser de qualidade alta.

**Johns Hopkins** no **Coursera** tem várias series de cursos muitas boas que abrange (como os de Harvard) R e R aplicada aos estudos biológicos. Roger Peng, Steven Salsburg, Jeff Leek, Brian Caffo e os demais professores têm boa didatica e expliquem bem o uso de R em estudos estatísticos. Pode começar com o curso seguinte para focar nas habilidades básicas de programação em R: https://www.coursera.org/learn/r-programming. 

**Utrecht University** em Holanda tem um curso introdutório, também excelente que ensina os conceitos básicos de R: https://github.com/UtrechtUniversity/workshop-introduction-to-R-and-data. Os slides do curso foram traduzidos à português por Dr. Diego Mazzotti da UNIFESP e agora da Universidade de Pennsylvania. Os slides deles são em nosso repo de Github com a permissão dele e vai reconhecer as porções que dos slides que eu emprestei com a permissão do Dr. Mazzotti e da Utrecht.

**Duke University** no **Coursera** também tem uma sequência dos cursos liderada por Profa. Mine Cetinkaya-Rundel (agora da Universidade de Edinburgh, Escocia) que é um dos melhores professores de R que vi nos cursos virtuais. Pode começar aqui: https://www.coursera.org/learn/probability-intro?specialization=statistics

## Livros --- R, Programação e Análise dos Dados

Os livros seguintes são alguns entre meus preferidos. Tenho foco aqui só em livros que são de graça. Não pode sempre fazer um download de um livro -- só está disponível no internet -- todos valem muito a pena.

  - Irizzary, **Introduction to Data Science** (https://rafalab.github.io/dsbook; texto para cursos de HarvardX)
  - Ismay & Kim, **Statistical Inference via Data Science: A moderndive into R and the tidyverse** (https://moderndive.com/)
  - Navarro, **Learning statistics with R: A tutorial for psychology students and other beginners** (https://learningstatisticswithr.com/book/)
  - Peng, **R Programming for Data Science** (Leanpub & Bookdown)
  - Peng, Kross & Anderson, **Mastering Software Development in R** (Leanpub & Bookdown)
  - Tierney, **R Markdown for Scientists** (https://rmd4sci.njtierney.com/)
  - Wickham & Grolemund, **R for Data Science** (http://r4ds.had.co.nz ou O'Reilly)

Se você quer escolher só um, sugiro **R for Data Science** pelo inventor do Tidyverse que pode ler de graça na Internet. Se for dois, o segundo seria ou **Statistical Inference via Data Science: A moderndive into R and the tidyverse** ou **R Programming for Data Science** ou **Learning Statistics with R**. 

Todos os livros de Bookdown pode ser achados (de graça): https://bookdown.org/. Os livros de Leanpub você pode geralmente fazer um download de graça. 

## *Cheatsheets*

RStudio publica uma série de "*cheatsheets*", resumos dos comandos e funções de vários aspectos de programação com R. São excelentes e você deve guardar eles onde pode consultar eles rapidamente. Colocando todos os elementos das funções no lugar certo na ordem certa não é fácil. *Cheatsheets* tiram muito do sofrimento. Pode achar eles aqui: https://www.rstudio.com/resources/cheatsheets/

## Sites

Existem muito sites e blogs além de CRAN e RStudio (que apresentei no último capitulo) que são focados em R. Aqui vou listar só poucos que podem ajudar você resolver duvidas sobre comandos e funções de R. Não hesite de usar eles. Em geral, são muito bons e tem respostas às suas perguntas.

  - **R Bloggers** (https://www.r-bloggers.com/) um compêndio de 750 blogs sobre R; destila os melhores posts desses blogs. Tem coisas interessantes quase todos os dias.
  - **Tidyverse** (https://www.tidyverse.org/learn/) tem muito informação sobre R e os programas do Tidyverse. É a fonte mais perto aos autores dos programas de *tidyverse*
  - **MAD-Stat** (https://madstatbr.wordpress.com/) o blog meu sobre R, estatística e bioestatística
  - **Stack Overflow** (https://stackoverflow.com/questions/tagged/r) um centro de esperteza em R e outros assuntos. Pode fazer perguntas depois que você escaneia se alguém respondeu para a mesma pergunta anterior. Se você quer postar no site, siga as recomendações sobre qual informação precisa dar para alguém responder. Os "experts" aqui não têm muito paciência infelizmente. Entretanto, este é o lugar onde vai achar respostas valiosas e vale a pena procurar uma solução aqui.
  
## Canal de Vídeo

Como eu disse no último capitulo, coloco vídeos nesse canal para ajudar você com questões que não são suficientemente explicadas em outros recursos. Se você tem uma duvida sobre um ponto, pode pedir que eu faça um vídeo sobre ele e vou postar. Para lembrar, o canal fica aqui: https://www.youtube.com/channel/UCbvgZ8RYeTtgjhAKE-jub5A

## Sistema de Ajuda de R e RStudio

O sistema de ajuda de R é muito completo. Toda função tem uma tela de ajuda. Uma das abas no RStudio (na janela a direta para baixo) é "*Help*" e você rapidamente ficará acostumado a consultar para achar a gramatica correta de usar nas funções. Mas, lembre que a documentação foi escrito por programadores, não romancistas ou jornalistas. Talvez pode ser difícil de entender as vezes. 

Começa com suas duvidas no sistema de *Help*, mas procure outros fontes de help se você não entende o texto lá facilmente. 

Se você tem uma pergunta e não acha uma solução facilmente ou recebe um mensagem de erro incompreensível, não hesite de copiar e colar a duvida ou mensagem em Google. Quase todas as duvidas que você pode ter já foram perguntadas por outros iniciantes de R e Google vai mandar você ver soluções uteis em Stack Overflow, R Bloggers e muito outros sites.

## Um Pensamento Final --- Perguntas

Pergunte bastante. Você não aprenda sem ter duvidas e perguntar para outros para ajudar resolver elas. Lembre que se você tem uma duvida, provavelmente outros tem a mesma duvida. Você não é só ajudando si mesmo; você está ajudando o grupo inteiro. **Não existem perguntas burras.** Como disse Carl Sagan (o astrofisico famoso que chefiou a versão original do programa de televisão "Cosmos": [^3]
  
>There are naive questions, tedious questions, ill-phrased questions, questions put after inadequate self-criticism. But every question is a cry to understand the world. **There is no such thing as a dumb question.** 

[^3]: Carl Sagan, **The Demon-Haunted World: Science as a Candle in the Dark**, p. 303.
